import fs from 'fs'
import path from 'path'
import Promise from 'bluebird'
import _ from 'lodash'

import {
  toJSON,
  getServices,
  getMessages,
  getModels,
  getMutationTypes,
  getActions,
} from '../src/protobuf'
import {
  generateImportCode,
  generateMutationTypesCode,
  generateInitGrpcCode,
  generateRequestCode,
  generateActionsCode,
  generateFileByProtoc,
  generateCode,
} from '../src/generator'

const proto = `
  syntax = "proto3";

  package helloworld;

  service Greeter {
    rpc SayHello (HelloRequest) returns (HelloReply);
  }

  message HelloRequest {
    message User {
      string name = 1;
      int32 age = 2;
      repeated string children = 3;
    }
    repeated User users = 1;
  }

  message HelloReply {
    message User {
      string name = 1;
      int32 age = 2;
      repeated string children = 3;
    }
    repeated User users = 1;
  }
`

describe('generateFileByProtoc', ()=>{
  beforeAll(()=>{
    return Promise.resolve()
      .then(()=>{
        const dirPath = '.grpc-vuex'
        if ( !fs.existsSync(dirPath) ) {
          return Promise.promisify(fs.mkdir)(dirPath)
        }
      })
      .then(()=>Promise.all([
        Promise.promisify(fs.stat)('./.grpc-vuex/helloworld_grpc_web_pb.js'),
        Promise.promisify(fs.stat)('./.grpc-vuex/helloworld_pb.js')
      ]))
      .then(()=>{
        return Promise.all([
          Promise.promisify(fs.unlink)('./.grpc-vuex/helloworld_grpc_web_pb.js'),
          Promise.promisify(fs.unlink)('./.grpc-vuex/helloworld_pb.js'),
        ])
      }, ()=>{})
      .then(()=>generateFileByProtoc('./test/grpc/helloworld.proto'))
  })
  it('returns code generated by Protoc', ()=>{
    return Promise
      .all([
        Promise.promisify(fs.stat)('./.grpc-vuex/helloworld_grpc_web_pb.js'),
        Promise.promisify(fs.stat)('./.grpc-vuex/helloworld_pb.js')
      ])
      .then(()=>{
        expect(true).toBeTruthy()
      })
  })
})

describe('generateImportCode', ()=>{
  it('returns js code', () => {
    const json = toJSON(proto)
    const services = getServices(json)
    const actions = getActions(services)
    const code = generateImportCode('helloworld', actions)
    expect(code).toBe(
`import GRPC from './grpc'
import { createRequest } from './request'
import { GreeterPromiseClient } from './helloworld_grpc_web_pb'
import { HelloRequest } from './helloworld_pb'`
    )
  })
})

describe('generateMutationTypesCode', ()=>{
  it('returns js code', () => {
    const json = toJSON(proto)
    const services = getServices(json)
    const mutationTypes = getMutationTypes(services)
    const code = generateMutationTypesCode(mutationTypes)
    expect(code).toBe(
`export const types = {
  GREETER_SAYHELLO: 'GREETER_SAYHELLO',
}`
    )
  })
})

describe('generateInitGrpcCode', ()=>{
  it('returns js code', () => {
    const endpoint = 'http://localhost:8080/'
    const code = generateInitGrpcCode(endpoint)
    expect(code).toBe(`export const grpc = new GRPC('${endpoint}')`)
  })
})

describe('generateRequestCode', ()=>{
  it('returns js code', () => {
    const code = generateRequestCode('HelloRequest', {users: 'User'})
    expect(code).toBe(`const req = createRequest(params, HelloRequest, {users:HelloRequest.User})`)
  })
})

describe('generateActionsCode', ()=>{
  it('returns js code', () => {
    const json = toJSON(proto)
    const services = getServices(json)
    const messages = getMessages(json)
    const models = getModels(messages)
    const actions = getActions(services)
    const code = generateActionsCode(actions, models)
    expect(code).toBe(
`export function sayHello (params, options) {
  const req = createRequest(params, HelloRequest, {users:HelloRequest.User})
  return grpc.call({
      client: GreeterPromiseClient,
      method: 'sayHello',
      req,
    })
    .then((res)=>{
      if (options && options.hasMutation) context.commit(types.GREETER_SAYHELLO, res)
      return res
    })
}`
    )
  })
})

describe('generateCode', ()=>{
  const protoFilePath = './test/grpc/helloworld.proto'
  const protoFileNameWithoutExt =  path.basename(protoFilePath, '.proto')
  beforeAll(()=>{
    return generateFileByProtoc(protoFilePath)
  })
  it('returns js code', () => {
    const json = toJSON(proto)
    const services = getServices(json)
    const messages = getMessages(json)
    const models = getModels(messages)
    const mutationTypes = getMutationTypes(services)
    const actions = getActions(services)
    const code = generateCode({
      protoFileNameWithoutExt,
      mutationTypes,
      actions,
      models,
      endpoint: 'http://localhost:8080/',
    })
    expect(_.isString(code)).toBeTruthy()
  })
})
