/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

goog.exportSymbol('proto.planet.Planet', null, global);
goog.exportSymbol('proto.planet.PlanetReply', null, global);
goog.exportSymbol('proto.planet.PlanetRequest', null, global);

/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.planet.Planet = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.planet.Planet.repeatedFields_, null);
};
goog.inherits(proto.planet.Planet, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.planet.Planet.displayName = 'proto.planet.Planet';
}
/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.planet.Planet.repeatedFields_ = [3];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.planet.Planet.prototype.toObject = function(opt_includeInstance) {
  return proto.planet.Planet.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.planet.Planet} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.planet.Planet.toObject = function(includeInstance, msg) {
  var f, obj = {
    name: jspb.Message.getFieldWithDefault(msg, 1, ""),
    age: jspb.Message.getFieldWithDefault(msg, 2, 0),
    satelliteList: jspb.Message.getRepeatedField(msg, 3)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.planet.Planet}
 */
proto.planet.Planet.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.planet.Planet;
  return proto.planet.Planet.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.planet.Planet} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.planet.Planet}
 */
proto.planet.Planet.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setName(value);
      break;
    case 2:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setAge(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.addSatellite(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.planet.Planet.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.planet.Planet.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.planet.Planet} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.planet.Planet.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getName();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getAge();
  if (f !== 0) {
    writer.writeInt32(
      2,
      f
    );
  }
  f = message.getSatelliteList();
  if (f.length > 0) {
    writer.writeRepeatedString(
      3,
      f
    );
  }
};


/**
 * optional string name = 1;
 * @return {string}
 */
proto.planet.Planet.prototype.getName = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/** @param {string} value */
proto.planet.Planet.prototype.setName = function(value) {
  jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional int32 age = 2;
 * @return {number}
 */
proto.planet.Planet.prototype.getAge = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 2, 0));
};


/** @param {number} value */
proto.planet.Planet.prototype.setAge = function(value) {
  jspb.Message.setProto3IntField(this, 2, value);
};


/**
 * repeated string satellite = 3;
 * @return {!Array<string>}
 */
proto.planet.Planet.prototype.getSatelliteList = function() {
  return /** @type {!Array<string>} */ (jspb.Message.getRepeatedField(this, 3));
};


/** @param {!Array<string>} value */
proto.planet.Planet.prototype.setSatelliteList = function(value) {
  jspb.Message.setField(this, 3, value || []);
};


/**
 * @param {!string} value
 * @param {number=} opt_index
 */
proto.planet.Planet.prototype.addSatellite = function(value, opt_index) {
  jspb.Message.addToRepeatedField(this, 3, value, opt_index);
};


proto.planet.Planet.prototype.clearSatelliteList = function() {
  this.setSatelliteList([]);
};



/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.planet.PlanetRequest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.planet.PlanetRequest.repeatedFields_, null);
};
goog.inherits(proto.planet.PlanetRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.planet.PlanetRequest.displayName = 'proto.planet.PlanetRequest';
}
/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.planet.PlanetRequest.repeatedFields_ = [1];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.planet.PlanetRequest.prototype.toObject = function(opt_includeInstance) {
  return proto.planet.PlanetRequest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.planet.PlanetRequest} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.planet.PlanetRequest.toObject = function(includeInstance, msg) {
  var f, obj = {
    planetList: jspb.Message.toObjectList(msg.getPlanetList(),
    proto.planet.Planet.toObject, includeInstance)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.planet.PlanetRequest}
 */
proto.planet.PlanetRequest.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.planet.PlanetRequest;
  return proto.planet.PlanetRequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.planet.PlanetRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.planet.PlanetRequest}
 */
proto.planet.PlanetRequest.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.planet.Planet;
      reader.readMessage(value,proto.planet.Planet.deserializeBinaryFromReader);
      msg.addPlanet(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.planet.PlanetRequest.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.planet.PlanetRequest.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.planet.PlanetRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.planet.PlanetRequest.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getPlanetList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      1,
      f,
      proto.planet.Planet.serializeBinaryToWriter
    );
  }
};


/**
 * repeated Planet planet = 1;
 * @return {!Array<!proto.planet.Planet>}
 */
proto.planet.PlanetRequest.prototype.getPlanetList = function() {
  return /** @type{!Array<!proto.planet.Planet>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.planet.Planet, 1));
};


/** @param {!Array<!proto.planet.Planet>} value */
proto.planet.PlanetRequest.prototype.setPlanetList = function(value) {
  jspb.Message.setRepeatedWrapperField(this, 1, value);
};


/**
 * @param {!proto.planet.Planet=} opt_value
 * @param {number=} opt_index
 * @return {!proto.planet.Planet}
 */
proto.planet.PlanetRequest.prototype.addPlanet = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 1, opt_value, proto.planet.Planet, opt_index);
};


proto.planet.PlanetRequest.prototype.clearPlanetList = function() {
  this.setPlanetList([]);
};



/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.planet.PlanetReply = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.planet.PlanetReply.repeatedFields_, null);
};
goog.inherits(proto.planet.PlanetReply, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.planet.PlanetReply.displayName = 'proto.planet.PlanetReply';
}
/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.planet.PlanetReply.repeatedFields_ = [1];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.planet.PlanetReply.prototype.toObject = function(opt_includeInstance) {
  return proto.planet.PlanetReply.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.planet.PlanetReply} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.planet.PlanetReply.toObject = function(includeInstance, msg) {
  var f, obj = {
    planetList: jspb.Message.toObjectList(msg.getPlanetList(),
    proto.planet.Planet.toObject, includeInstance)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.planet.PlanetReply}
 */
proto.planet.PlanetReply.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.planet.PlanetReply;
  return proto.planet.PlanetReply.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.planet.PlanetReply} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.planet.PlanetReply}
 */
proto.planet.PlanetReply.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.planet.Planet;
      reader.readMessage(value,proto.planet.Planet.deserializeBinaryFromReader);
      msg.addPlanet(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.planet.PlanetReply.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.planet.PlanetReply.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.planet.PlanetReply} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.planet.PlanetReply.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getPlanetList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      1,
      f,
      proto.planet.Planet.serializeBinaryToWriter
    );
  }
};


/**
 * repeated Planet planet = 1;
 * @return {!Array<!proto.planet.Planet>}
 */
proto.planet.PlanetReply.prototype.getPlanetList = function() {
  return /** @type{!Array<!proto.planet.Planet>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.planet.Planet, 1));
};


/** @param {!Array<!proto.planet.Planet>} value */
proto.planet.PlanetReply.prototype.setPlanetList = function(value) {
  jspb.Message.setRepeatedWrapperField(this, 1, value);
};


/**
 * @param {!proto.planet.Planet=} opt_value
 * @param {number=} opt_index
 * @return {!proto.planet.Planet}
 */
proto.planet.PlanetReply.prototype.addPlanet = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 1, opt_value, proto.planet.Planet, opt_index);
};


proto.planet.PlanetReply.prototype.clearPlanetList = function() {
  this.setPlanetList([]);
};


goog.object.extend(exports, proto.planet);
